// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: pkg/proto/data_node.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       string                 `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadDataRequest) Reset() {
	*x = DownloadDataRequest{}
	mi := &file_pkg_proto_data_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadDataRequest) ProtoMessage() {}

func (x *DownloadDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_data_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadDataRequest.ProtoReflect.Descriptor instead.
func (*DownloadDataRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_data_node_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadDataRequest) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

// 数据分片信息
type DataChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ChunkTotal    int32                  `protobuf:"varint,2,opt,name=chunk_total,json=chunkTotal,proto3" json:"chunk_total,omitempty"`
	ChunkId       int32                  `protobuf:"varint,3,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"` // 当前分片 ID（从1开始）
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                 // 实际数据负载
	FileSize      int64                  `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataChunk) Reset() {
	*x = DataChunk{}
	mi := &file_pkg_proto_data_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataChunk) ProtoMessage() {}

func (x *DataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_data_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChunk.ProtoReflect.Descriptor instead.
func (*DataChunk) Descriptor() ([]byte, []int) {
	return file_pkg_proto_data_node_proto_rawDescGZIP(), []int{1}
}

func (x *DataChunk) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *DataChunk) GetChunkTotal() int32 {
	if x != nil {
		return x.ChunkTotal
	}
	return 0
}

func (x *DataChunk) GetChunkId() int32 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

func (x *DataChunk) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DataChunk) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type UploadDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDataResponse) Reset() {
	*x = UploadDataResponse{}
	mi := &file_pkg_proto_data_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDataResponse) ProtoMessage() {}

func (x *UploadDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_data_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDataResponse.ProtoReflect.Descriptor instead.
func (*UploadDataResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_data_node_proto_rawDescGZIP(), []int{2}
}

func (x *UploadDataResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_pkg_proto_data_node_proto protoreflect.FileDescriptor

const file_pkg_proto_data_node_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/proto/data_node.proto\x12\x05proto\"/\n" +
	"\x13DownloadDataRequest\x12\x18\n" +
	"\arequest\x18\x01 \x01(\tR\arequest\"\x9b\x01\n" +
	"\tDataChunk\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1f\n" +
	"\vchunk_total\x18\x02 \x01(\x05R\n" +
	"chunkTotal\x12\x19\n" +
	"\bchunk_id\x18\x03 \x01(\x05R\achunkId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\x03R\bfileSize\"0\n" +
	"\x12UploadDataResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse2\x92\x01\n" +
	"\x0fDataNodeService\x12@\n" +
	"\fDownloadData\x12\x1a.proto.DownloadDataRequest\x1a\x10.proto.DataChunk(\x010\x01\x12=\n" +
	"\n" +
	"UploadData\x12\x10.proto.DataChunk\x1a\x19.proto.UploadDataResponse(\x010\x01B\fZ\n" +
	"/pkg/protob\x06proto3"

var (
	file_pkg_proto_data_node_proto_rawDescOnce sync.Once
	file_pkg_proto_data_node_proto_rawDescData []byte
)

func file_pkg_proto_data_node_proto_rawDescGZIP() []byte {
	file_pkg_proto_data_node_proto_rawDescOnce.Do(func() {
		file_pkg_proto_data_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_data_node_proto_rawDesc), len(file_pkg_proto_data_node_proto_rawDesc)))
	})
	return file_pkg_proto_data_node_proto_rawDescData
}

var file_pkg_proto_data_node_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_data_node_proto_goTypes = []any{
	(*DownloadDataRequest)(nil), // 0: proto.DownloadDataRequest
	(*DataChunk)(nil),           // 1: proto.DataChunk
	(*UploadDataResponse)(nil),  // 2: proto.UploadDataResponse
}
var file_pkg_proto_data_node_proto_depIdxs = []int32{
	0, // 0: proto.DataNodeService.DownloadData:input_type -> proto.DownloadDataRequest
	1, // 1: proto.DataNodeService.UploadData:input_type -> proto.DataChunk
	1, // 2: proto.DataNodeService.DownloadData:output_type -> proto.DataChunk
	2, // 3: proto.DataNodeService.UploadData:output_type -> proto.UploadDataResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_data_node_proto_init() }
func file_pkg_proto_data_node_proto_init() {
	if File_pkg_proto_data_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_data_node_proto_rawDesc), len(file_pkg_proto_data_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_data_node_proto_goTypes,
		DependencyIndexes: file_pkg_proto_data_node_proto_depIdxs,
		MessageInfos:      file_pkg_proto_data_node_proto_msgTypes,
	}.Build()
	File_pkg_proto_data_node_proto = out.File
	file_pkg_proto_data_node_proto_goTypes = nil
	file_pkg_proto_data_node_proto_depIdxs = nil
}
