// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: pkg/proto/metadata_node.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents the information stored per file/key in the metastore
type ChunkInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`                   // Unique identifier for the chunk (could be filename + sequence, or hash)
	ChunkLocation string                 `protobuf:"bytes,2,opt,name=chunk_location,json=chunkLocation,proto3" json:"chunk_location,omitempty"` // Node address (e.g., "host:port") or identifier where the chunk resides
	ChunkStatus   string                 `protobuf:"bytes,3,opt,name=chunk_status,json=chunkStatus,proto3" json:"chunk_status,omitempty"`       // Status like "available", "replicating", "lost" etc. (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkInfo) Reset() {
	*x = ChunkInfo{}
	mi := &file_pkg_proto_metadata_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkInfo) ProtoMessage() {}

func (x *ChunkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_metadata_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkInfo.ProtoReflect.Descriptor instead.
func (*ChunkInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_metadata_node_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkInfo) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ChunkInfo) GetChunkLocation() string {
	if x != nil {
		return x.ChunkLocation
	}
	return ""
}

func (x *ChunkInfo) GetChunkStatus() string {
	if x != nil {
		return x.ChunkStatus
	}
	return ""
}

// --- ProposeSet ---
type ProposeSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // The key (e.g., filename) for the metadata
	Value         *ChunkInfo             `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // The metadata value to set
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeSetRequest) Reset() {
	*x = ProposeSetRequest{}
	mi := &file_pkg_proto_metadata_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeSetRequest) ProtoMessage() {}

func (x *ProposeSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_metadata_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeSetRequest.ProtoReflect.Descriptor instead.
func (*ProposeSetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_metadata_node_proto_rawDescGZIP(), []int{1}
}

func (x *ProposeSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ProposeSetRequest) GetValue() *ChunkInfo {
	if x != nil {
		return x.Value
	}
	return nil
}

type ProposeSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                              // Indicates if the proposal was accepted by the node (doesn't guarantee commit yet)
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Optional error details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeSetResponse) Reset() {
	*x = ProposeSetResponse{}
	mi := &file_pkg_proto_metadata_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeSetResponse) ProtoMessage() {}

func (x *ProposeSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_metadata_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeSetResponse.ProtoReflect.Descriptor instead.
func (*ProposeSetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_metadata_node_proto_rawDescGZIP(), []int{2}
}

func (x *ProposeSetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProposeSetResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// --- GetMetadata ---
type GetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // The key (e.g., filename) to retrieve
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_pkg_proto_metadata_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_metadata_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_metadata_node_proto_rawDescGZIP(), []int{3}
}

func (x *GetMetadataRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *ChunkInfo             `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`                                   // The retrieved metadata
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`                                  // True if the key was found
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Optional error details (e.g., key not found)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataResponse) Reset() {
	*x = GetMetadataResponse{}
	mi := &file_pkg_proto_metadata_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResponse) ProtoMessage() {}

func (x *GetMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_metadata_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_metadata_node_proto_rawDescGZIP(), []int{4}
}

func (x *GetMetadataResponse) GetValue() *ChunkInfo {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetMetadataResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetMetadataResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// --- ProposeDelete ---
type ProposeDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // The key (e.g., filename) to delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeDeleteRequest) Reset() {
	*x = ProposeDeleteRequest{}
	mi := &file_pkg_proto_metadata_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeDeleteRequest) ProtoMessage() {}

func (x *ProposeDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_metadata_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeDeleteRequest.ProtoReflect.Descriptor instead.
func (*ProposeDeleteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_metadata_node_proto_rawDescGZIP(), []int{5}
}

func (x *ProposeDeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ProposeDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                              // Indicates if the proposal was accepted by the node
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Optional error details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeDeleteResponse) Reset() {
	*x = ProposeDeleteResponse{}
	mi := &file_pkg_proto_metadata_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeDeleteResponse) ProtoMessage() {}

func (x *ProposeDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_metadata_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeDeleteResponse.ProtoReflect.Descriptor instead.
func (*ProposeDeleteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_metadata_node_proto_rawDescGZIP(), []int{6}
}

func (x *ProposeDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProposeDeleteResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_pkg_proto_metadata_node_proto protoreflect.FileDescriptor

const file_pkg_proto_metadata_node_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/proto/metadata_node.proto\x12\x05proto\"p\n" +
	"\tChunkInfo\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12%\n" +
	"\x0echunk_location\x18\x02 \x01(\tR\rchunkLocation\x12!\n" +
	"\fchunk_status\x18\x03 \x01(\tR\vchunkStatus\"M\n" +
	"\x11ProposeSetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.proto.ChunkInfoR\x05value\"S\n" +
	"\x12ProposeSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"&\n" +
	"\x12GetMetadataRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"x\n" +
	"\x13GetMetadataResponse\x12&\n" +
	"\x05value\x18\x01 \x01(\v2\x10.proto.ChunkInfoR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"(\n" +
	"\x14ProposeDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"V\n" +
	"\x15ProposeDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\xe6\x01\n" +
	"\x0fMetadataService\x12A\n" +
	"\n" +
	"ProposeSet\x12\x18.proto.ProposeSetRequest\x1a\x19.proto.ProposeSetResponse\x12D\n" +
	"\vGetMetadata\x12\x19.proto.GetMetadataRequest\x1a\x1a.proto.GetMetadataResponse\x12J\n" +
	"\rProposeDelete\x12\x1b.proto.ProposeDeleteRequest\x1a\x1c.proto.ProposeDeleteResponseB\fZ\n" +
	"/pkg/protob\x06proto3"

var (
	file_pkg_proto_metadata_node_proto_rawDescOnce sync.Once
	file_pkg_proto_metadata_node_proto_rawDescData []byte
)

func file_pkg_proto_metadata_node_proto_rawDescGZIP() []byte {
	file_pkg_proto_metadata_node_proto_rawDescOnce.Do(func() {
		file_pkg_proto_metadata_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_metadata_node_proto_rawDesc), len(file_pkg_proto_metadata_node_proto_rawDesc)))
	})
	return file_pkg_proto_metadata_node_proto_rawDescData
}

var file_pkg_proto_metadata_node_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_metadata_node_proto_goTypes = []any{
	(*ChunkInfo)(nil),             // 0: proto.ChunkInfo
	(*ProposeSetRequest)(nil),     // 1: proto.ProposeSetRequest
	(*ProposeSetResponse)(nil),    // 2: proto.ProposeSetResponse
	(*GetMetadataRequest)(nil),    // 3: proto.GetMetadataRequest
	(*GetMetadataResponse)(nil),   // 4: proto.GetMetadataResponse
	(*ProposeDeleteRequest)(nil),  // 5: proto.ProposeDeleteRequest
	(*ProposeDeleteResponse)(nil), // 6: proto.ProposeDeleteResponse
}
var file_pkg_proto_metadata_node_proto_depIdxs = []int32{
	0, // 0: proto.ProposeSetRequest.value:type_name -> proto.ChunkInfo
	0, // 1: proto.GetMetadataResponse.value:type_name -> proto.ChunkInfo
	1, // 2: proto.MetadataService.ProposeSet:input_type -> proto.ProposeSetRequest
	3, // 3: proto.MetadataService.GetMetadata:input_type -> proto.GetMetadataRequest
	5, // 4: proto.MetadataService.ProposeDelete:input_type -> proto.ProposeDeleteRequest
	2, // 5: proto.MetadataService.ProposeSet:output_type -> proto.ProposeSetResponse
	4, // 6: proto.MetadataService.GetMetadata:output_type -> proto.GetMetadataResponse
	6, // 7: proto.MetadataService.ProposeDelete:output_type -> proto.ProposeDeleteResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_metadata_node_proto_init() }
func file_pkg_proto_metadata_node_proto_init() {
	if File_pkg_proto_metadata_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_metadata_node_proto_rawDesc), len(file_pkg_proto_metadata_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_metadata_node_proto_goTypes,
		DependencyIndexes: file_pkg_proto_metadata_node_proto_depIdxs,
		MessageInfos:      file_pkg_proto_metadata_node_proto_msgTypes,
	}.Build()
	File_pkg_proto_metadata_node_proto = out.File
	file_pkg_proto_metadata_node_proto_goTypes = nil
	file_pkg_proto_metadata_node_proto_depIdxs = nil
}
